import {expect, test} from '@playwright/test';
import {PDFDocument} from 'pdf-lib';
import {readFile} from 'node:fs/promises';
import {createDesign, interpretDesignRequest, type DesignDocument} from '@ugoku/core';
import {manual, stage, startSample, selectPdfMode, saveProject} from './helpers';

// Ordinary deterministic app path. No inference client is created by these tests.
test('one request field and review replace normal controls without changing the design before adoption', async ({page}, info) => {
  await page.goto('/'); await startSample(page); await manual(page);
  const base = await page.locator('main').getAttribute('data-design-hash');
  await expect(page.locator('textarea#design-intent')).toHaveCount(1);
  await expect(page.locator('.helper-switch')).toHaveCount(0);
  await page.getByLabel('どう動かしたいですか？').fill('あと5mm動かしたい。絵の大きさと紙の枚数は変えない');
  await page.getByRole('button',{name:'寸法から案をつくる',exact:true}).click();
  await expect(page.locator('.candidate-workbench')).toBeVisible();
  await expect(page.locator('.motion-settings')).toBeHidden();
  await expect(page.locator('#workbench')).toBeHidden();
  await expect(page.locator('main')).toHaveAttribute('data-design-hash',base!);
  const views=page.locator('.candidate-workbench svg');
  expect(await views.nth(0).getAttribute('viewBox')).toBe(await views.nth(1).getAttribute('viewBox'));
  await expect(page.locator('.change-table')).toContainText('25mm');
  await expect(page.locator('.interpretation-details')).not.toHaveAttribute('open','');
  if(info.project.name==='mobile') {
    await page.setViewportSize({width:320,height:844});
    await page.getByRole('button',{name:'いまの作品',exact:true}).click();
    await expect(page.locator('.comparison-before')).toBeVisible(); await expect(page.locator('.comparison-after')).toBeHidden();
    await page.getByRole('button',{name:'候補の作品',exact:true}).click();
    await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  }
  await page.getByRole('button',{name:'この案を使わない',exact:true}).click();
  await expect(page.locator('.motion-settings')).toBeVisible();
  await expect(page.locator('main')).toHaveAttribute('data-design-hash',base!);
  await manual(page); await page.getByRole('button',{name:'寸法から案をつくる',exact:true}).click();
  await page.getByRole('button',{name:'この案にする',exact:true}).click();
  await expect(page.getByLabel('動く距離（mm）',{exact:true})).toHaveValue('25');
  const adopted=await page.locator('main').getAttribute('data-design-hash');
  await stage(page,3); await selectPdfMode(page, 'pattern');
  const download=page.waitForEvent('download'); await page.getByRole('button',{name:'PDFをダウンロード',exact:true}).click();
  const file=await download;const path=info.outputPath('adopted-pattern.pdf');await file.saveAs(path);
  const pdf=await PDFDocument.load(await readFile(path));expect(pdf.getSubject()).toContain(adopted);expect(pdf.getPages()[0]!.getWidth()).toBeCloseTo(595.276,2);
});

test('failed validation shows each geometry reason once and preserves errors without a detailed issue list', async({page}, info)=>{
  let base: DesignDocument;
  let firstReason = '', firstSuggestion = '', starts = 0;
  const noIssuesMessage = '検査の詳細を取得できませんでした。作品は変更していません。接続を確認して再試行してください。';
  await page.route('**/api/status',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({ai:{enabled:true,mode:'injected-test',reason:'テスト専用の応答'},limits:{modelCalls:6,toolCalls:12,timeoutMs:90000,inputBytes:20000,outputTokens:1000}})}));
  await page.route('**/api/sessions',async route=>{base=route.request().postDataJSON().document;await route.continue();});
  await page.route('**/api/sessions/**/runs',route=>{
    starts++;
    const input=route.request().postDataJSON();
    const invalid=createDesign({...base.input,travelMm:70},{designId:base.designId,revision:base.revision+1});
    const issues=invalid.checks.filter(check=>check.status==='fail');
    expect(issues.length).toBeGreaterThan(0);
    firstReason=issues[0]!.message;firstSuggestion=issues[0]!.suggestion!;
    const message=starts===1 ? `候補は条件を満たしません。${issues[0]!.partIds.join('・')}：${firstReason} ${firstSuggestion}` : noIssuesMessage;
    const run={requestInterpretation:interpretDesignRequest(base,input.prompt),id:`validation-test-${starts}`,requestId:input.requestId,baseRevision:input.baseRevision,baseHash:input.baseHash,mode:'injected-test',status:'failed',message,error:{code:'validation_failed',message},validationIssues:starts===1?issues:[],constraintSuggestions:[],events:[],modelCalls:0,toolCalls:0,elapsedMs:0};
    return route.fulfill({contentType:'application/json',body:JSON.stringify({run})});
  });
  await page.goto('/');await startSample(page);await manual(page);
  await page.getByLabel('絵の大きさを保つ', {exact:true}).check();
  await page.getByLabel('どう動かしたいですか？').fill('70mm動かしたい。絵の大きさと紙の枚数は変えない');
  const original = await saveProject(page);
  const stamp=await page.locator('main').evaluate(element=>({hash:element.dataset.designHash,revision:element.dataset.designRevision}));
  await page.getByRole('button',{name:'設定',exact:true}).click();
  await page.getByLabel('AIアクセスコード').fill('synthetic-validation-access');
  await page.getByRole('dialog',{name:'設定',exact:true}).getByRole('button',{name:'閉じる',exact:true}).click();
  await page.getByRole('button',{name:'AIで案をつくる',exact:true}).click();
  const panel=page.locator('.ai-panel');
  await expect(panel.getByRole('status')).toHaveText('希望70mm。この条件では未成立です。作品と固定条件は変更していません。下の理由を確認し、変更してよい条件を見直してください。');
  const text=await panel.innerText();
  expect(text.split(firstReason)).toHaveLength(2);
  expect(text.split(firstSuggestion)).toHaveLength(2);
  await expect(panel.getByRole('heading',{name:'設計で見つかった問題'})).toBeVisible();
  await expect(panel.getByRole('button',{name:'この案にする',exact:true})).toHaveCount(0);
  await expect(page.locator('main')).toHaveAttribute('data-design-hash',stamp.hash!);
  await expect(page.locator('main')).toHaveAttribute('data-design-revision',stamp.revision!);
  await expect(panel.getByRole('button',{name:'条件を見直す',exact:true})).toBeVisible();
  await panel.screenshot({path:info.outputPath('infeasible-result.png')});
  await panel.getByRole('button',{name:'条件を見直す',exact:true}).click();
  await expect(page.locator('.motion-settings')).toBeVisible();
  const preserved = await saveProject(page);
  expect(preserved.document).toEqual(original.document);
  await page.screenshot({path:info.outputPath('infeasible-manual-recovery.png')});
  await page.getByRole('button',{name:'AIを再試行する',exact:true}).click();
  await expect(panel.getByRole('status')).toHaveText(noIssuesMessage);
  await expect(panel.getByRole('heading',{name:'設計で見つかった問題'})).toHaveCount(0);
  await panel.getByRole('button',{name:'手動の調整に戻る',exact:true}).click();
  await expect(page.locator('.motion-settings')).toBeVisible();
  await expect(page.locator('main')).toHaveAttribute('data-design-hash',stamp.hash!);
  const distance = page.getByLabel('動く距離（mm）',{exact:true});
  await distance.fill('18'); await distance.press('Enter');
  await page.getByRole('button',{name:'元に戻す',exact:true}).click();
  await page.getByRole('button',{name:'やり直す',exact:true}).click();
  await expect(distance).toHaveValue('18');
  await page.getByRole('button',{name:'元に戻す',exact:true}).click();
  const restored=await saveProject(page);
  expect(restored.document.designHash).toBe(original.document.designHash);
  expect(restored.document.input.locks).toEqual(original.document.input.locks);
  expect(restored.document.revision).toBeGreaterThan(original.document.revision);
  expect(starts).toBe(2);
});

test('local configuration is confined to Settings and no ordinary edit starts inference', async({page})=>{
  let starts=0;
  await page.route('**/api/status',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({ai:{enabled:true,provider:'ollama',mode:'ollama',model:'local-test-model',endpoint:'http://127.0.0.1:11434',contextLength:8192,toolMode:'native'},limits:{modelCalls:6,toolCalls:12,timeoutMs:90000,inputBytes:20000,outputTokens:1000}})}));
  await page.route('**/api/sessions/**/runs',route=>{starts++;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'provider_unavailable',message:'ローカルAIに接続できません。現在の作品は残っています。'}})});});
  await page.goto('/');await startSample(page);await stage(page,2);
  await expect(page.getByText('モデル：local-test-model',{exact:true})).toBeHidden();
  const distance=page.getByLabel('動く距離（mm）',{exact:true});await distance.fill('18');await distance.press('Enter');
  await page.getByRole('button',{name:'動かす',exact:true}).click();await page.getByRole('button',{name:'動きを停止',exact:true}).click();
  await expect(page.locator('main')).toHaveAttribute('data-save-status','saved'); expect(starts).toBe(0);
  await page.getByRole('button',{name:'設定',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'設定',exact:true});
  await expect(dialog.getByRole('heading',{name:'ローカルAI',exact:true})).toBeVisible();
  await expect(dialog).toContainText('外部の推論APIへ自動で切り替えません');await expect(dialog).toContainText('127.0.0.1:11434');
  await page.getByLabel('AIアクセスコード').fill('synthetic-local-access');await dialog.getByRole('button',{name:'閉じる',exact:true}).click();
  await manual(page);await page.getByRole('button',{name:'AIで案をつくる',exact:true}).click();
  await expect(page.locator('.ai-panel')).toContainText('ローカルAIに接続できません');expect(starts).toBe(1);
  await expect(distance).toHaveValue('18');await expect(page.getByRole('button',{name:'手動の調整に戻る',exact:true})).toBeVisible();
});
